// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeStatusDto
 */
export interface ChangeStatusDto {
    /**
     * 
     * @type {string}
     * @memberof ChangeStatusDto
     */
    status: ChangeStatusDtoStatusEnum;
}


/**
 * @export
 */
export const ChangeStatusDtoStatusEnum = {
    NotDone: 'NOT_DONE',
    Done: 'DONE'
} as const;
export type ChangeStatusDtoStatusEnum = typeof ChangeStatusDtoStatusEnum[keyof typeof ChangeStatusDtoStatusEnum];


/**
 * Check if a given object implements the ChangeStatusDto interface.
 */
export function instanceOfChangeStatusDto(value: object): value is ChangeStatusDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ChangeStatusDtoFromJSON(json: any): ChangeStatusDto {
    return ChangeStatusDtoFromJSONTyped(json, false);
}

export function ChangeStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ChangeStatusDtoToJSON(value?: ChangeStatusDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

