// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskDto
 */
export interface CreateTaskDto {
    /**
     * Title of the task
     * @type {string}
     * @memberof CreateTaskDto
     */
    title: string;
    /**
     * Description of the task
     * @type {string}
     * @memberof CreateTaskDto
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateTaskDto interface.
 */
export function instanceOfCreateTaskDto(value: object): value is CreateTaskDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateTaskDtoFromJSON(json: any): CreateTaskDto {
    return CreateTaskDtoFromJSONTyped(json, false);
}

export function CreateTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateTaskDtoToJSON(value?: CreateTaskDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

