// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAuthPayload
 */
export interface EmailAuthPayload {
    /**
     * User's email address
     * @type {string}
     * @memberof EmailAuthPayload
     */
    email: string;
    /**
     * User's password
     * @type {string}
     * @memberof EmailAuthPayload
     */
    password: string;
}

/**
 * Check if a given object implements the EmailAuthPayload interface.
 */
export function instanceOfEmailAuthPayload(value: object): value is EmailAuthPayload {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function EmailAuthPayloadFromJSON(json: any): EmailAuthPayload {
    return EmailAuthPayloadFromJSONTyped(json, false);
}

export function EmailAuthPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAuthPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function EmailAuthPayloadToJSON(value?: EmailAuthPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

