// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteUserDto
 */
export interface InviteUserDto {
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    email: string;
    /**
     * Role to assign to the invited user
     * @type {string}
     * @memberof InviteUserDto
     */
    role: InviteUserDtoRoleEnum;
}


/**
 * @export
 */
export const InviteUserDtoRoleEnum = {
    Worker: 'WORKER',
    Admin: 'ADMIN',
    Viewer: 'VIEWER'
} as const;
export type InviteUserDtoRoleEnum = typeof InviteUserDtoRoleEnum[keyof typeof InviteUserDtoRoleEnum];


/**
 * Check if a given object implements the InviteUserDto interface.
 */
export function instanceOfInviteUserDto(value: object): value is InviteUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function InviteUserDtoFromJSON(json: any): InviteUserDto {
    return InviteUserDtoFromJSONTyped(json, false);
}

export function InviteUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'],
    };
}

export function InviteUserDtoToJSON(value?: InviteUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'role': value['role'],
    };
}

