// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshPayload
 */
export interface RefreshPayload {
    /**
     * Refresh token for obtaining new access tokens
     * @type {string}
     * @memberof RefreshPayload
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshPayload interface.
 */
export function instanceOfRefreshPayload(value: object): value is RefreshPayload {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshPayloadFromJSON(json: any): RefreshPayload {
    return RefreshPayloadFromJSONTyped(json, false);
}

export function RefreshPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshPayloadToJSON(value?: RefreshPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'refreshToken': value['refreshToken'],
    };
}

