// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveUserDto
 */
export interface RemoveUserDto {
    /**
     * 
     * @type {number}
     * @memberof RemoveUserDto
     */
    userId: number;
}

/**
 * Check if a given object implements the RemoveUserDto interface.
 */
export function instanceOfRemoveUserDto(value: object): value is RemoveUserDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function RemoveUserDtoFromJSON(json: any): RemoveUserDto {
    return RemoveUserDtoFromJSONTyped(json, false);
}

export function RemoveUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function RemoveUserDtoToJSON(value?: RemoveUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

