// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskListControllerRemoveUserRequest
 */
export interface TaskListControllerRemoveUserRequest {
    /**
     * ID of the user to remove
     * @type {number}
     * @memberof TaskListControllerRemoveUserRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the TaskListControllerRemoveUserRequest interface.
 */
export function instanceOfTaskListControllerRemoveUserRequest(value: object): value is TaskListControllerRemoveUserRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function TaskListControllerRemoveUserRequestFromJSON(json: any): TaskListControllerRemoveUserRequest {
    return TaskListControllerRemoveUserRequestFromJSONTyped(json, false);
}

export function TaskListControllerRemoveUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskListControllerRemoveUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function TaskListControllerRemoveUserRequestToJSON(value?: TaskListControllerRemoveUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

