// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskDto
 */
export interface UpdateTaskDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    status?: UpdateTaskDtoStatusEnum;
}


/**
 * @export
 */
export const UpdateTaskDtoStatusEnum = {
    NotDone: 'NOT_DONE',
    Done: 'DONE'
} as const;
export type UpdateTaskDtoStatusEnum = typeof UpdateTaskDtoStatusEnum[keyof typeof UpdateTaskDtoStatusEnum];


/**
 * Check if a given object implements the UpdateTaskDto interface.
 */
export function instanceOfUpdateTaskDto(value: object): value is UpdateTaskDto {
    return true;
}

export function UpdateTaskDtoFromJSON(json: any): UpdateTaskDto {
    return UpdateTaskDtoFromJSONTyped(json, false);
}

export function UpdateTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateTaskDtoToJSON(value?: UpdateTaskDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
    };
}

