// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserTaskList } from './UserTaskList';
import {
    UserTaskListFromJSON,
    UserTaskListFromJSONTyped,
    UserTaskListToJSON,
} from './UserTaskList';

/**
 * 
 * @export
 * @interface UserTaskListPaginationResult
 */
export interface UserTaskListPaginationResult {
    /**
     * Array of items
     * @type {Array<UserTaskList>}
     * @memberof UserTaskListPaginationResult
     */
    data: Array<UserTaskList>;
    /**
     * Total number of items
     * @type {number}
     * @memberof UserTaskListPaginationResult
     */
    total: number;
    /**
     * Current page number
     * @type {number}
     * @memberof UserTaskListPaginationResult
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof UserTaskListPaginationResult
     */
    limit: number;
}

/**
 * Check if a given object implements the UserTaskListPaginationResult interface.
 */
export function instanceOfUserTaskListPaginationResult(value: object): value is UserTaskListPaginationResult {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function UserTaskListPaginationResultFromJSON(json: any): UserTaskListPaginationResult {
    return UserTaskListPaginationResultFromJSONTyped(json, false);
}

export function UserTaskListPaginationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTaskListPaginationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserTaskListFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function UserTaskListPaginationResultToJSON(value?: UserTaskListPaginationResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(UserTaskListToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

