// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API endpoints and details
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTaskListDto,
  InviteUserDto,
  RemoveUserDto,
  TaskList,
  UpdateProjectDto,
  UserTaskList,
  UserTaskListPaginationResult,
} from '../models/index';
import {
    CreateTaskListDtoFromJSON,
    CreateTaskListDtoToJSON,
    InviteUserDtoFromJSON,
    InviteUserDtoToJSON,
    RemoveUserDtoFromJSON,
    RemoveUserDtoToJSON,
    TaskListFromJSON,
    TaskListToJSON,
    UpdateProjectDtoFromJSON,
    UpdateProjectDtoToJSON,
    UserTaskListFromJSON,
    UserTaskListToJSON,
    UserTaskListPaginationResultFromJSON,
    UserTaskListPaginationResultToJSON,
} from '../models/index';

export interface TaskListControllerCreateRequest {
    createTaskListDto: CreateTaskListDto;
}

export interface TaskListControllerGetAllRequest {
    page?: number;
    limit?: number;
}

export interface TaskListControllerGetAllParticipantsRequest {
    taskListId: string;
    page?: number;
    limit?: number;
}

export interface TaskListControllerGetByIdRequest {
    taskListId: string;
}

export interface TaskListControllerGetMyUserTaskListRequest {
    taskListId: string;
}

export interface TaskListControllerInviteUserRequest {
    taskListId: string;
    inviteUserDto: InviteUserDto;
}

export interface TaskListControllerLeaveRequest {
    taskListId: string;
}

export interface TaskListControllerRemoveUserRequest {
    taskListId: string;
    removeUserDto: RemoveUserDto;
}

export interface TaskListControllerUpdateRequest {
    taskListId: string;
    updateProjectDto: UpdateProjectDto;
}

/**
 * 
 */
export class TaskListApi extends runtime.BaseAPI {

    /**
     * Create a new project
     */
    async taskListControllerCreateRaw(requestParameters: TaskListControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskList>> {
        if (requestParameters['createTaskListDto'] == null) {
            throw new runtime.RequiredError(
                'createTaskListDto',
                'Required parameter "createTaskListDto" was null or undefined when calling taskListControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTaskListDtoToJSON(requestParameters['createTaskListDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskListFromJSON(jsonValue));
    }

    /**
     * Create a new project
     */
    async taskListControllerCreate(requestParameters: TaskListControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskList> {
        const response = await this.taskListControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all projects for the current user
     */
    async taskListControllerGetAllRaw(requestParameters: TaskListControllerGetAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserTaskListPaginationResult>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserTaskListPaginationResultFromJSON(jsonValue));
    }

    /**
     * Get all projects for the current user
     */
    async taskListControllerGetAll(requestParameters: TaskListControllerGetAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserTaskListPaginationResult> {
        const response = await this.taskListControllerGetAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all projects for the current user
     */
    async taskListControllerGetAllParticipantsRaw(requestParameters: TaskListControllerGetAllParticipantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserTaskListPaginationResult>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerGetAllParticipants().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}/participants`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserTaskListPaginationResultFromJSON(jsonValue));
    }

    /**
     * Get all projects for the current user
     */
    async taskListControllerGetAllParticipants(requestParameters: TaskListControllerGetAllParticipantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserTaskListPaginationResult> {
        const response = await this.taskListControllerGetAllParticipantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a project by its ID
     */
    async taskListControllerGetByIdRaw(requestParameters: TaskListControllerGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskList>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskListFromJSON(jsonValue));
    }

    /**
     * Get a project by its ID
     */
    async taskListControllerGetById(requestParameters: TaskListControllerGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskList> {
        const response = await this.taskListControllerGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current users taskList connection
     */
    async taskListControllerGetMyUserTaskListRaw(requestParameters: TaskListControllerGetMyUserTaskListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserTaskList>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerGetMyUserTaskList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}/me`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserTaskListFromJSON(jsonValue));
    }

    /**
     * Get current users taskList connection
     */
    async taskListControllerGetMyUserTaskList(requestParameters: TaskListControllerGetMyUserTaskListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserTaskList> {
        const response = await this.taskListControllerGetMyUserTaskListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invite a user to the project
     */
    async taskListControllerInviteUserRaw(requestParameters: TaskListControllerInviteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserTaskList>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerInviteUser().'
            );
        }

        if (requestParameters['inviteUserDto'] == null) {
            throw new runtime.RequiredError(
                'inviteUserDto',
                'Required parameter "inviteUserDto" was null or undefined when calling taskListControllerInviteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}/users/invite`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InviteUserDtoToJSON(requestParameters['inviteUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserTaskListFromJSON(jsonValue));
    }

    /**
     * Invite a user to the project
     */
    async taskListControllerInviteUser(requestParameters: TaskListControllerInviteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserTaskList> {
        const response = await this.taskListControllerInviteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a user from the project
     */
    async taskListControllerLeaveRaw(requestParameters: TaskListControllerLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserTaskList>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerLeave().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}/leave`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserTaskListFromJSON(jsonValue));
    }

    /**
     * Remove a user from the project
     */
    async taskListControllerLeave(requestParameters: TaskListControllerLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserTaskList> {
        const response = await this.taskListControllerLeaveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a user from the project
     */
    async taskListControllerRemoveUserRaw(requestParameters: TaskListControllerRemoveUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserTaskList>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerRemoveUser().'
            );
        }

        if (requestParameters['removeUserDto'] == null) {
            throw new runtime.RequiredError(
                'removeUserDto',
                'Required parameter "removeUserDto" was null or undefined when calling taskListControllerRemoveUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}/users/remove`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: RemoveUserDtoToJSON(requestParameters['removeUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserTaskListFromJSON(jsonValue));
    }

    /**
     * Remove a user from the project
     */
    async taskListControllerRemoveUser(requestParameters: TaskListControllerRemoveUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserTaskList> {
        const response = await this.taskListControllerRemoveUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update project details
     */
    async taskListControllerUpdateRaw(requestParameters: TaskListControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskList>> {
        if (requestParameters['taskListId'] == null) {
            throw new runtime.RequiredError(
                'taskListId',
                'Required parameter "taskListId" was null or undefined when calling taskListControllerUpdate().'
            );
        }

        if (requestParameters['updateProjectDto'] == null) {
            throw new runtime.RequiredError(
                'updateProjectDto',
                'Required parameter "updateProjectDto" was null or undefined when calling taskListControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{taskListId}`.replace(`{${"taskListId"}}`, encodeURIComponent(String(requestParameters['taskListId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectDtoToJSON(requestParameters['updateProjectDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskListFromJSON(jsonValue));
    }

    /**
     * Update project details
     */
    async taskListControllerUpdate(requestParameters: TaskListControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskList> {
        const response = await this.taskListControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
